# Generated by Django 6.0.6 on 2026-06-13 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tienda", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="productos/"),
        ),
    ]
